2016/01/04 11:49:22 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "themes/flaty/index.html".' in F:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('themes/flaty/in...', NULL, true)
#1 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): CController->render('themes/flaty/in...')
#2 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 11:49:42 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "themes/flaty/code/index.html".' in F:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('themes/flaty/co...', NULL, true)
#1 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): CController->render('themes/flaty/co...')
#2 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 11:49:52 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "/themes/flaty/code/index.html".' in F:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('/themes/flaty/c...', NULL, true)
#1 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): CController->render('/themes/flaty/c...')
#2 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 11:50:03 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "../themes/flaty/code/index.html".' in F:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('../themes/flaty...', NULL, true)
#1 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): CController->render('../themes/flaty...')
#2 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 12:33:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index
---
2016/01/04 12:34:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index
---
2016/01/04 12:34:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index
---
2016/01/04 12:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index
---
2016/01/04 12:35:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index
---
2016/01/04 12:35:10 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:35:12 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:35:15 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:35:16 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:36:55 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:37:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index.php".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index...')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index.php
---
2016/01/04 12:37:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index.php".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index...')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index.php
---
2016/01/04 12:37:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index
---
2016/01/04 12:37:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index.html".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index...')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index.html
---
2016/01/04 12:37:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dashboard/index.html".' in F:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dashboard/index...')
#1 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/ssc_haf/index.php?r=dashboard/index.html
---
2016/01/04 12:38:46 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('dashboard/index', NULL, true)
#1 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): CController->render('dashboard/index')
#2 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 12:39:27 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:40:08 [error] [php] strpos() expects parameter 1 to be string, array given (F:\xampp\htdocs\yii\framework\web\CController.php:706)
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(586): CTheme->getViewFile()
#1 F:\xampp\htdocs\yii\framework\web\CController.php(867): SiteController->getViewFile()
#2 F:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): SiteController->render()
#4 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 F:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 F:\xampp\htdocs\ssc_haf\index.php(13): CWebApplication->run()
REQUEST_URI=/ssc_haf/
in F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php (32)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 12:43:07 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "dashboard/index".' in F:\xampp\htdocs\yii\framework\web\CController.php:878
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('dashboard/index', NULL, true)
#1 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(32): CController->render('dashboard/index')
#2 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 14:46:25 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT COUNT(*) FROM AuthItem
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RInstaller.php (180)
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\controllers\InstallController.php (43)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 14:46:25 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such table: AuthItem. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RInstaller.php (180)
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\controllers\InstallController.php (43)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 14:46:50 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 F:\xampp\htdocs\ssc_haf\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 F:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 F:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 F:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 F:\xampp\htdocs\ssc_haf\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/ssc_haf/index.php?r=user/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=user/login
---
2016/01/04 14:52:11 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 F:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 F:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 F:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(94): CModel->validate()
#9 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/login
---
2016/01/04 14:52:58 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 F:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 F:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 F:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(94): CModel->validate()
#9 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/login
---
2016/01/04 14:54:36 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 F:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 F:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 F:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(94): CModel->validate()
#9 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/login
---
2016/01/04 14:55:22 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 F:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 F:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 F:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(94): CModel->validate()
#9 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/login
---
2016/01/04 15:01:00 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "User" cannot be found in the database.' in F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 F:\xampp\htdocs\ssc_haf\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 F:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 F:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 F:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(94): CModel->validate()
#9 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/login
---
2016/01/04 15:24:54 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nussc.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid.
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RAuthorizer.php (341)
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RWebUser.php (21)
in F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php (71)
2016/01/04 15:24:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nussc.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid' in F:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 F:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RAuthorizer.php(341): CDbAuthManager->getAuthAssignments('1')
#3 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('1')
#4 F:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(246): RWebUser->afterLogin(false)
#5 F:\xampp\htdocs\ssc_haf\protected\models\LoginForm.php(71): CWebUser->login(Object(UserIdentity), 0)
#6 F:\xampp\htdocs\ssc_haf\protected\controllers\SiteController.php(94): LoginForm->login()
#7 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/login
---
2016/01/04 15:26:33 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nussc.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RInstaller.php (180)
in F:\xampp\htdocs\ssc_haf\protected\modules\rights\controllers\InstallController.php (43)
in F:\xampp\htdocs\ssc_haf\index.php (13)
2016/01/04 15:38:33 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=user/login
---
2016/01/04 15:38:36 [error] [exception.CException] exception 'CException' with message 'Property "ProfileField.range" is not defined.' in F:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('range')
#1 F:\xampp\htdocs\ssc_haf\protected\modules\user\views\profile\profile.php(34): CActiveRecord->__get('range')
#2 F:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('F:\\xampp\\htdocs...')
#3 F:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\\xampp\\htdocs...', Array, true)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('F:\\xampp\\htdocs...', Array, true)
#5 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('profile', Array, true)
#6 F:\xampp\htdocs\ssc_haf\protected\modules\user\controllers\ProfileController.php(21): CController->render('profile', Array)
#7 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ProfileController->actionProfile()
#8 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/profile')
#13 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/ssc_haf/index.php?r=user/profile
HTTP_REFERER=http://localhost/ssc_haf/index.php
---
2016/01/04 15:38:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/roles
---
2016/01/04 15:38:41 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('roles')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/roles
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/operations
---
2016/01/04 15:38:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('operations')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/operations
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/tasks
---
2016/01/04 15:38:46 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:39:08 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('operations')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/operations
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/tasks
---
2016/01/04 15:39:09 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('tasks')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/tasks
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/roles
---
2016/01/04 15:39:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('roles')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/roles
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/permissions
---
2016/01/04 15:39:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('permissions')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/permissions
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/assignment/view
---
2016/01/04 15:39:11 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/assignme...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/assignment/view
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights
---
2016/01/04 15:39:12 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights
HTTP_REFERER=http://localhost/ssc_haf/index.php
---
2016/01/04 15:39:13 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights
---
2016/01/04 15:39:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights
HTTP_REFERER=http://localhost/ssc_haf/index.php
---
2016/01/04 15:39:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/roles
---
2016/01/04 15:39:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('roles')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/roles
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/tasks
---
2016/01/04 15:39:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('tasks')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/tasks
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/authItem/operations
---
2016/01/04 15:39:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('operations')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/operations
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights
---
2016/01/04 15:39:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=user/login
---
2016/01/04 15:39:18 [error] [exception.CException] exception 'CException' with message 'Property "ProfileField.range" is not defined.' in F:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('range')
#1 F:\xampp\htdocs\ssc_haf\protected\modules\user\views\profile\profile.php(34): CActiveRecord->__get('range')
#2 F:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('F:\\xampp\\htdocs...')
#3 F:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\\xampp\\htdocs...', Array, true)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('F:\\xampp\\htdocs...', Array, true)
#5 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('profile', Array, true)
#6 F:\xampp\htdocs\ssc_haf\protected\modules\user\controllers\ProfileController.php(21): CController->render('profile', Array)
#7 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ProfileController->actionProfile()
#8 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/profile')
#13 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/ssc_haf/index.php?r=user/profile
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=user/login
---
2016/01/04 15:39:25 [error] [exception.CException] exception 'CException' with message 'Property "ProfileField.range" is not defined.' in F:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('range')
#1 F:\xampp\htdocs\ssc_haf\protected\modules\user\views\profile\profile.php(34): CActiveRecord->__get('range')
#2 F:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('F:\\xampp\\htdocs...')
#3 F:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\\xampp\\htdocs...', Array, true)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('F:\\xampp\\htdocs...', Array, true)
#5 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('profile', Array, true)
#6 F:\xampp\htdocs\ssc_haf\protected\modules\user\controllers\ProfileController.php(21): CController->render('profile', Array)
#7 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ProfileController->actionProfile()
#8 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/profile')
#13 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/ssc_haf/index.php?r=user/profile
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=site/index
---
2016/01/04 15:39:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/index
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=rights/install/ready
---
2016/01/04 15:39:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php
---
2016/01/04 15:39:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
---
2016/01/04 15:39:35 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/login
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=user/login
---
2016/01/04 15:39:36 [error] [exception.CException] exception 'CException' with message 'Property "ProfileField.range" is not defined.' in F:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 F:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('range')
#1 F:\xampp\htdocs\ssc_haf\protected\modules\user\views\profile\profile.php(34): CActiveRecord->__get('range')
#2 F:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('F:\\xampp\\htdocs...')
#3 F:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('F:\\xampp\\htdocs...', Array, true)
#4 F:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('F:\\xampp\\htdocs...', Array, true)
#5 F:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('profile', Array, true)
#6 F:\xampp\htdocs\ssc_haf\protected\modules\user\controllers\ProfileController.php(21): CController->render('profile', Array)
#7 F:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ProfileController->actionProfile()
#8 F:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 F:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#12 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/profile')
#13 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/ssc_haf/index.php?r=user/profile
---
2016/01/04 15:39:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php/rights/install
---
2016/01/04 15:39:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:39:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:40:43 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:40:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:40:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('logout')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/logout
---
2016/01/04 15:41:03 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('logout')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/logout
---
2016/01/04 15:41:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('logout')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/logout')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=site/logout
---
2016/01/04 15:44:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 F:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(RWebUser), 'You are not aut...')
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/authItem...')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php?r=rights/authItem/
---
2016/01/04 15:44:33 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:46:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/
---
2016/01/04 15:51:52 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php:62
Stack trace:
#0 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(57): RController->accessDenied()
#1 F:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#2 F:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#3 F:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#4 F:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 F:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 F:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 F:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 F:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 F:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/ssc_haf/index.php
HTTP_REFERER=http://localhost/ssc_haf/index.php?r=user/login
---
2016/01/06 06:27:27 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nussc.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `authassignment`
WHERE userid=:userid.
in C:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RWebUser.php (43)
in C:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php (43)
in C:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php (36)
2016/01/06 06:27:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nussc.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `authassignment`
WHERE userid=:userid' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(74): CDbAuthManager->getAuthAssignments(NULL)
#3 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(815): CDbAuthManager->checkAccess('Site.*', NULL, Array)
#4 C:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RWebUser.php(43): CWebUser->checkAccess('Site.*', Array, true)
#5 C:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RightsFilter.php(43): RWebUser->checkAccess('Site.*')
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): RightsFilter->preFilter(Object(CFilterChain))
#7 C:\xampp\htdocs\ssc_haf\protected\modules\rights\components\RController.php(36): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): RController->filterRights(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\ssc_haf\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/ssc_haf/
---
